name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_timezone: Asia/Bishkek
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year    
          plugin_languages: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, use
          plugin_achievements: yes
          plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, Contributor, maintainer, developer,
              scripter, packager, explorer
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
